### ISSUE TITLE
ISA E?

### ISSUE THREAD

**Issue by krause24** [dpimley/riscv#1]
Looks like there is a subset of the ISA for embedded applications that only defines 16 registers. Should we use it?

**Comment by dpimley** [comment]
Can you link it? I'll take a look

**Comment by krause24** [comment]
https://github.com/riscv/riscv-isa-manual/releases/tag/draft-20191016-1342267

Chapter 4 in the spec pdf

**Comment by dpimley** [comment]
Yeah I'm fine with that, will take out the possibility of floating point. Not sure if you guys wanted to do that though.

**Comment by krause24** [comment]
Cool, it's decided. We can save floating point for the next one we do. ISA E it is
